
package com.fictional.ibank.card.ccms.xmlmodel;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2015-11-14T18:16:58.682+08:00
 * Generated source version: 3.1.4
 *
 */
public final class CardCustomerService_CardCustomerService_Client {

    private static final QName SERVICE_NAME = new QName("http://services.cards.common.scb", "CardCustomerService");

    private CardCustomerService_CardCustomerService_Client() {
    }

    public static void oldmain(String args[]) throws java.lang.Exception {
        URL wsdlURL = CardCustomerService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        CardCustomerService_Service ss = new CardCustomerService_Service(wsdlURL, SERVICE_NAME);
        CardCustomerService port = ss.getCardCustomerService();

        {
        System.out.println("Invoking enquireCardCustomer...");
        com.fictional.ibank.card.ccms.xmlmodel.ServiceHeader _enquireCardCustomer_serviceHeader = new com.fictional.ibank.card.ccms.xmlmodel.ServiceHeader();
        com.fictional.ibank.card.ccms.xmlmodel.CardCustomer _enquireCardCustomer_enquireCardCustomer = new com.fictional.ibank.card.ccms.xmlmodel.CardCustomer();
        try {
            com.fictional.ibank.card.ccms.xmlmodel.CardCustomer _enquireCardCustomer__return = port.enquireCardCustomer(_enquireCardCustomer_serviceHeader, _enquireCardCustomer_enquireCardCustomer);
            System.out.println("enquireCardCustomer.result=" + _enquireCardCustomer__return);

        } catch (SecurityFault_Exception e) {
            System.out.println("Expected exception: SecurityFault has occurred.");
            System.out.println(e.toString());
        } catch (ServiceFault_Exception e) {
            System.out.println("Expected exception: ServiceFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getMerchantDetails...");
        com.fictional.ibank.card.ccms.xmlmodel.ServiceHeader _getMerchantDetails_serviceheader = new com.fictional.ibank.card.ccms.xmlmodel.ServiceHeader();
        com.fictional.ibank.card.ccms.xmlmodel.CreditCard _getMerchantDetails_getMerchantDetailsRq = new com.fictional.ibank.card.ccms.xmlmodel.CreditCard();
        try {
            com.fictional.ibank.card.ccms.xmlmodel.CreditCard _getMerchantDetails__return = port.getMerchantDetails(_getMerchantDetails_serviceheader, _getMerchantDetails_getMerchantDetailsRq);
            System.out.println("getMerchantDetails.result=" + _getMerchantDetails__return);

        } catch (SecurityFault_Exception e) {
            System.out.println("Expected exception: SecurityFault has occurred.");
            System.out.println(e.toString());
        } catch (ServiceFault_Exception e) {
            System.out.println("Expected exception: ServiceFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getRewardRedemptionDetails...");
        com.fictional.ibank.card.ccms.xmlmodel.ServiceHeader _getRewardRedemptionDetails_serviceheader = new com.fictional.ibank.card.ccms.xmlmodel.ServiceHeader();
        com.fictional.ibank.card.ccms.xmlmodel.CardCustomer _getRewardRedemptionDetails_getRewardRedemptionDetailsRq = new com.fictional.ibank.card.ccms.xmlmodel.CardCustomer();
        try {
            com.fictional.ibank.card.ccms.xmlmodel.CardCustomer _getRewardRedemptionDetails__return = port.getRewardRedemptionDetails(_getRewardRedemptionDetails_serviceheader, _getRewardRedemptionDetails_getRewardRedemptionDetailsRq);
            System.out.println("getRewardRedemptionDetails.result=" + _getRewardRedemptionDetails__return);

        } catch (SecurityFault_Exception e) {
            System.out.println("Expected exception: SecurityFault has occurred.");
            System.out.println(e.toString());
        } catch (ServiceFault_Exception e) {
            System.out.println("Expected exception: ServiceFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking enquireLinkedCards...");
        com.fictional.ibank.card.ccms.xmlmodel.ServiceHeader _enquireLinkedCards_serviceHeader = new com.fictional.ibank.card.ccms.xmlmodel.ServiceHeader();
        com.fictional.ibank.card.ccms.xmlmodel.CardCustomer _enquireLinkedCards_enquireLinkedCards = new com.fictional.ibank.card.ccms.xmlmodel.CardCustomer();
        try {
            com.fictional.ibank.card.ccms.xmlmodel.CardCustomer _enquireLinkedCards__return = port.enquireLinkedCards(_enquireLinkedCards_serviceHeader, _enquireLinkedCards_enquireLinkedCards);
            System.out.println("enquireLinkedCards.result=" + _enquireLinkedCards__return);

        } catch (SecurityFault_Exception e) {
            System.out.println("Expected exception: SecurityFault has occurred.");
            System.out.println(e.toString());
        } catch (ServiceFault_Exception e) {
            System.out.println("Expected exception: ServiceFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getCustomerRewardPointsSummary...");
        com.fictional.ibank.card.ccms.xmlmodel.ServiceHeader _getCustomerRewardPointsSummary_serviceHeader = new com.fictional.ibank.card.ccms.xmlmodel.ServiceHeader();
        com.fictional.ibank.card.ccms.xmlmodel.CardCustomer _getCustomerRewardPointsSummary_getCustomerRewardPointsSummaryRq = new com.fictional.ibank.card.ccms.xmlmodel.CardCustomer();
        try {
            com.fictional.ibank.card.ccms.xmlmodel.CardCustomer _getCustomerRewardPointsSummary__return = port.getCustomerRewardPointsSummary(_getCustomerRewardPointsSummary_serviceHeader, _getCustomerRewardPointsSummary_getCustomerRewardPointsSummaryRq);
            System.out.println("getCustomerRewardPointsSummary.result=" + _getCustomerRewardPointsSummary__return);

        } catch (SecurityFault_Exception e) {
            System.out.println("Expected exception: SecurityFault has occurred.");
            System.out.println(e.toString());
        } catch (ServiceFault_Exception e) {
            System.out.println("Expected exception: ServiceFault has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
