@javax.xml.bind.annotation.XmlSchema(namespace = "http://entity.cards.common.scb", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.fictional.ibank.card.ccms.xmlmodel;

/*

The files in this package were generated by wsdl2java in CXF.

The tool may complain about unable to find XSD files during generation. If so, just temporarily modify the WSDL file to include
full URL (or path) of the XSD files.

CardCustomerService_Service.java was manually modified to remove reference to hard coded WSDL file path.

 */
