
package com.fictional.ibank.card.ccms.xmlmodel;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.4
 * 2015-11-14T18:16:58.783+08:00
 * Generated source version: 3.1.4
 */

@WebFault(name = "ServiceFault", targetNamespace = "http://fault.service.common.scb")
public class ServiceFault_Exception extends Exception {
    
    private com.fictional.ibank.card.ccms.xmlmodel.ServiceFault serviceFault;

    public ServiceFault_Exception() {
        super();
    }
    
    public ServiceFault_Exception(String message) {
        super(message);
    }
    
    public ServiceFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public ServiceFault_Exception(String message, com.fictional.ibank.card.ccms.xmlmodel.ServiceFault serviceFault) {
        super(message);
        this.serviceFault = serviceFault;
    }

    public ServiceFault_Exception(String message, com.fictional.ibank.card.ccms.xmlmodel.ServiceFault serviceFault, Throwable cause) {
        super(message, cause);
        this.serviceFault = serviceFault;
    }

    public com.fictional.ibank.card.ccms.xmlmodel.ServiceFault getFaultInfo() {
        return this.serviceFault;
    }
}
