
drop table ibank_cards if exists;

create table ibank_cards (
 id bigint generated by default as identity,
 country_code varchar(3) not null,
 customer_id varchar(10) not null,
 product_name varchar(32) not null,
 balance decimal(10,4) not null,
 avail_limit decimal(10,4) not null,
 expiry_date date,
 last_update timestamp default current_timestamp,
 primary key (id)
 );
