#! /bin/bash

if [ "$DOCKER_MACHINE_NAME" = "" ]; then
  echo DOCKER_MACHINE_NAME is not set. unable to continue
  exit 1
fi


DOCKER_HOST_IP=$(docker-machine inspect --format='{{.Driver.IPAddress}}' $DOCKER_MACHINE_NAME)
if [ "$DOCKER_HOST_IP" = "" ]; then
  echo unable to determine IP address of docker machine $DOCKER_MACHINE_NAME. is it running?
  exit 1
fi

export PUBLIC_BASE_URL=http://$DOCKER_HOST_IP:8080

if [ "$DB_TYPE" = "" ]; then
  DB_TYPE=h2
fi

./shutdown.sh > /dev/null 2>&1

#DB_TYPE=mysql

# would be nice if IP address can be parsed from env
export DB_TYPE
export MYSQL_HOST=192.168.99.1

if [ "$DOCKER_REGISTRY_PREFIX" = "" ]; then
  export DOCKER_REGISTRY_PREFIX="sloppycoder"
fi

echo Starting application using docker-compose
docker-compose up -d

./wait_for_app.sh

echo Your application should be available at $PUBLIC_BASE_URL/app
