
drop table csl_customers if exists;

create table csl_customers (
 id bigint generated by default as identity,
 country_code varchar(3) not null,
 customer_id varchar(10) not null,
 login varchar(32) not null,
 customer_name varchar(100) not null,
 last_upate timestamp default current_timestamp,
 primary key (id)
 );

